# Generated by Django 3.1.6 on 2021-02-01 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('Type', models.CharField(choices=[('AC', 'AC'), ('NON-AC', 'NON-AC')], max_length=10)),
                ('Bed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check_in', models.DateTimeField()),
                ('Check_out', models.DateTimeField()),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finflex.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
