# Generated by Django 3.1.6 on 2021-02-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finflex', '0002_auto_20210201_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
